### ISSUE TITLE
[Bug] «CR» line break symbol on ends of lines

### ISSUE THREAD

**Issue by Kristinita** [divinites/gissues#49]
### Summary

`CR` in the ends of lines, when I select issue on issue list.
### Expected behavior

No `CR` line break symbol.
### Actual behavior

![СR on ends of lines](http://i.imgur.com/ERMasLk.png)
### Steps to reproduce

`GitHub Issues: List All Issues` → `divinites/gissues` → I select line 

> 19          0         [Bug] I can not begin to work 

→ I get `CR` on ends of lines.
### Environment

**Operating system and version:**
Windows 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by divinites** [comment]
could you please change the debug flag to 1, and show the console output please? Thanks.

**Comment by Kristinita** [comment]
Only this output. But `Киролайна` folder is not a git repository, but `Киролайна` is folder in top of my sidebar, see [this comment](https://github.com/divinites/gissues/issues/19#issuecomment-249765062).

```
command: show_github_issue
No git :( [Errno 2] No such file or directory: 'E:\\Киролайна\\.git\\HEAD'
```

Thanks.

**Comment by divinites** [comment]
After changing the debug flag, you will need to restart Sublime Text to let it take effect. You will have something like:

```
INFO:root:GitHub-Issue >>> using git
INFO:root:GitHub-Issue >>> repo address is https://github.com/divinites/gissues

INFO:root:GitHub-Issue >>> find username divinites and repo_name gissues
INFO:root:GitHub-Issue >>> using git
INFO:root:GitHub-Issue >>> repo address is https://github.com/divinites/gissues

INFO:root:GitHub-Issue >>> find username divinites and repo_name gissues
INFO:root:GitHub-Issue >>> I am showing the issue list!
INFO:root:GitHub-Issue >>> the joint url is https://api.github.com/repos/divinites/gissues/issues
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /repos/divinites/gissues/issues HTTP/1.1" 200 None
INFO:root:GitHub-Issue >>> found the view in repo_dictionary
INFO:root:GitHub-Issue >>> the joint url is https://api.github.com/repos/divinites/gissues/issues/50
DEBUG:requests.packages.urllib3.connectionpool:"GET /repos/divinites/gissues/issues/50 HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"GET /repos/divinites/gissues/issues/50/comments HTTP/1.1" 200 2
INFO:root:GitHub-Issue >>> filtering line ends
INFO:root:GitHub-Issue >>> Issue title [Feature request] Markdown syntax, which user is preferable, for GitHub issue creating formated

```

**Comment by Kristinita** [comment]
I have `"debug": 1` in my user settings → I change to `"debug": 0` → I restart Sublime Text → I change to `"debug": 1` → I restart Sublime Text. But I still have not output in console. Thanks.

**Comment by divinites** [comment]
So, "debug" find another bug ? :)

Anyway, I will try to find a way to make all the settings instantly take effect. Restarting every time is also annoying.

**Comment by Kristinita** [comment]
I get output information on Sublime Text without plugins and user settings. I have `CR` symbol on end of lines [this issue](https://github.com/divinites/gissues/issues/49).

```
INFO:root:GitHub-Issue >>> I am showing the issue list!
INFO:root:GitHub-Issue >>> username is nsubiron
INFO:root:GitHub-Issue >>> repo name is SublimeSuricate
INFO:root:GitHub-Issue >>> the joint url is https://api.github.com/repos/nsubiron/SublimeSuricate/issues
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: api.github.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /repos/nsubiron/SublimeSuricate/issues?state=all HTTP/1.1" 200 None
INFO:root:GitHub-Issue >>> found the view in repo_dictionary
INFO:root:GitHub-Issue >>> the joint url is https://api.github.com/repos/nsubiron/SublimeSuricate/issues/2
DEBUG:requests.packages.urllib3.connectionpool:"GET /repos/nsubiron/SublimeSuricate/issues/2 HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"GET /repos/nsubiron/SublimeSuricate/issues/2/comments HTTP/1.1" 200 None
INFO:root:GitHub-Issue >>> no need to fix issue line ends
INFO:root:GitHub-Issue >>> Issue title [Bug] Conflict with Package Control formated
INFO:root:GitHub-Issue >>> no need to fix issue line ends
INFO:root:GitHub-Issue >>> comment id 251605499formated
```

Thanks.

**Comment by divinites** [comment]
Thanks. 

As I guessed, this is the problem:

## INFO:root:GitHub-Issue >>> no need to fix issue line ends

INFO:root:GitHub-Issue >>> Issue title [Bug] Conflict with Package Control formated

## INFO:root:GitHub-Issue >>> no need to fix issue line ends

 INFO:root:GitHub-Issue >>> comment id 251605499formated

I will see to this problem right now.

**Comment by Kristinita** [comment]
Now I saw error in console:

> No git :( [Errno 2] No such file or directory: 'E:\Mega.co.nz\MEGAsync Загрузки\Джинджерины\Грейс Ло\.git\HEAD'

`Грейс Ло` also not git repository, but I move folder `Грейс Ло` in top of my sidebar. 

![Грейс Ло](http://i.imgur.com/Jluyqop.png)

If I disable GitHub Issue, error not reproduced.

Thanks.

**Comment by divinites** [comment]
solved by abc1e42.

**Comment by Kristinita** [comment]
@divinites, release?

**Comment by divinites** [comment]
@Kristinita 1.3.0, it will need a while to sync with package control channel.

**Comment by Kristinita** [comment]
@divinites , not solved for me. Moreover, CR now appear anywhere.

![CR](http://i.imgur.com/P9pNpzJ.png)

I have also [this error](https://github.com/divinites/gissues/issues/49#issuecomment-251656870) remains.

Thanks.

**Comment by divinites** [comment]
Could you please post your console debug information?

Also, what is your "default_line_ending" flag in Preferences.sublime-settings?

**Comment by Kristinita** [comment]
> Also, what is your "default_line_ending" flag in Preferences.sublime-settings?

I not change this setting. It turns out that `CRLF` — default value for windows.

> Could you please post your console debug information?

In my Sublime Text I can not get debug information, see [comment](https://github.com/divinites/gissues/issues/49#issuecomment-251617646).

Output in Sublime Text without plugins and user settings:

```
INFO:root:GitHub-Issue >>> The first 8 digits of your GitHub Token is ddb40937
INFO:root:GitHub-Issue >>> Your own username is Kristinita
INFO:root:GitHub-Issue >>> I am showing the issue list!
INFO:root:GitHub-Issue >>> username is divinites
INFO:root:GitHub-Issue >>> repo name is gissues
INFO:root:GitHub-Issue >>> the joint url is https://api.github.com/repos/divinites/gissues/issues
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /repos/divinites/gissues/issues?state=all HTTP/1.1" 200 None
```

**Comment by divinites** [comment]
@Kristinita Acutally, I am quite curious. It seems that If I really add 'CRLF' as the line ends, 'CR' will pop up every where; however, if I simply `set line_ends = /n`. Every thing works. At this moment, I commented out all codes related to line ends and simply use `/n`, it works perfect in both Windows and Mac. I pushed a 1.3.2 tag, please tell me your experience when you can update.

**Comment by divinites** [comment]
@Kristinita  I forgot the say, I restructured logging system, now debug flag should actually work, this should solve your comment [here](https://github.com/divinites/gissues/issues/49#issuecomment-251617646).

**Comment by Kristinita** [comment]
@divinites, `CR` problem was solved for me, thanks!

### Remaining errors:
1. I still not can get debugging information.  
   
   No git :( [Errno 2] No such file or directory: 'E:\Mega.co.nz\MEGAsync Загрузки\Джинджерины\Грейс Ло\.git\HEAD'  
2. When I update this issue:  

``` python
command: update_github_issue {}
Traceback (most recent call last):
  File "./python3.3/logging/__init__.py", line 941, in emit
  File "./python3.3/encodings/cp1251.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 1561: character maps to <undefined>
Logged from file GitHubIssue.sublime-package, line 203
```

### Feature Requests
1. Please, replace `GitHub Issue: Show Issue List` → `GitHub Issue: Show Open Issue List`. This caption name more clearly reflects the essence of the command being run.
2. Please, uncomment `github_issue.sublime-settings` file. Users can not edit settings use [Preference Editor](https://bitbucket.org/klorenz/sublimepreferenceseditor/src).

Thanks.

**Comment by divinites** [comment]
Feature Requests done, I am now working on pagniation, and will release all the three updates altogether. 
Just a small test of updating.→

**Comment by Kristinita** [comment]
@divinites , you not uncommented `github_issue.sublime-settings` file. Thanks.

**Comment by divinites** [comment]
@Kristinita  I do not understand. the current github_issue.sublime-settings is:

``` json
{
    "token": "",
    "username": "",
    "password": "",
    "debug": 0,
    "syntax": "Packages/GitHubIssue/Issue.sublime-syntax",
    "git_path": ""

}

```

I have already uncommented everything? Is it different on your side?

**Comment by Kristinita** [comment]
Version 1.5.5. For me all settings are comments.

``` json
{
    // "token": "",
    // "username": "",
    // "password": "",
    // "debug": 0,
    // "syntax": "",
    // "git_path": ""

}
```

Thanks.

**Comment by divinites** [comment]
It should not be like this. Could you please remove and re-install this packge?

**Comment by Kristinita** [comment]
@divinites , I have replaced the file to the correct. But I do not understand why `sublime-settings` file does not change when an automatic update via Package Control.

Thanks.

**Comment by Kristinita** [comment]
@divinites , I still get error `No git :( [Errno 2] No such file or directory:` https://github.com/divinites/gissues/issues/49#issuecomment-251656870 . Thanks.

**Comment by divinites** [comment]
@Kristinita does the plug-in work when you see this error? have you configured "git_path" in your github_issue.sublime-settings file? I have changed find_git function to address this issue.

**Comment by Kristinita** [comment]
> does the plug-in work when you see this error?

Yes, I get this error if GitHub Issue work.

I get this error in different time, for example:

```
key evt: alt+keypad6
chr evt: → (0x2192)
chr evt:   (0x20)
No git :( [Errno 2] No such file or directory: 'E:\\Mega.co.nz\\MEGAsync Загрузки\\Джинджерины\\Грейс Ло\\.git\\HEAD'

No git :( [Errno 2] No such file or directory: 'E:\\Mega.co.nz\\MEGAsync Загрузки\\Джинджерины\\Грейс Ло\\.git\\HEAD'
command: post_or_update_issue {}
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: api.github.com

key evt: shift+control+p
command: show_overlay {"overlay": "command_palette"}
No git :( [Errno 2] No such file or directory: 'E:\\Mega.co.nz\\MEGAsync Загрузки\\Джинджерины\\Грейс Ло\\.git\\HEAD'

key evt: backspace
command: left_delete
chr evt:   (0x20)
No git :( [Errno 2] No such file or directory: 'E:\\Mega.co.nz\\MEGAsync Загрузки\\Джинджерины\\Грейс Ло\\.git\\HEAD'
chr evt: в (0x432)
chr evt:   (0x20)

chr evt: I (0x49)
chr evt:   (0x20)
No git :( [Errno 2] No such file or directory: 'E:\\Mega.co.nz\\MEGAsync Загрузки\\Джинджерины\\Грейс Ло\\.git\\HEAD'
chr evt: o (0x6f)

key evt: control+p
command: show_overlay {"overlay": "goto", "show_files": true}
chr evt: T (0x54)
No git :( [Errno 2] No such file or directory: 'E:\\Mega.co.nz\\MEGAsync Загрузки\\Джинджерины\\Грейс Ло\\.git\\HEAD'
chr evt: e (0x65)
```

> have you configured "git_path" in your github_issue.sublime-settings file?

I add path to my `git.exe` file in my settings:

```
"git_path": "C:\\Program Files\\Git\\bin\\git.exe",
```

Thanks.

**Comment by divinites** [comment]
I still get no idea about this error :stuck_out_tongue_closed_eyes:

**Comment by divinites** [comment]
Hi, @Kristinita I finally solved this problem by completely removing `git` dependency. Now the plug-in will search `.git` directory in the root folder, and try to directly dig out the username and the repo_name from directory instead of relying on `git` command. So `git_path` flag is now deprecated. Could you please set `disable\_local\_repositories` to false and try run this plug-in? I bet you will never see something like this ever again.

```
No git :( [Errno 2] No such file or directory: 'E:\\Mega.co.nz\\MEGAsync Загрузки\\Джинджерины\\Грейс Ло\\.git\\HEAD'
```

The new version will be 2.7.0

## Update

The debug information problem is also solved by removing logging module. I think there is no obivous bug so I named the current version v3.0.0 with great pleasure.

**Comment by Kristinita** [comment]
Now problem reproduced for me, if I disable GitHub Issues. Likely, is not GitHub Issues bug.
