### ISSUE TITLE
Would it be possible to disable vintage/vintageous when viewing the issue list

### ISSUE THREAD

**Issue by docsteveharris** [divinites/gissues#97]
e.g. `view.settings().set('__vi_external_disable', True)`

see https://github.com/guillermooo/Vintageous/wiki/Disabling

and implemented here for sublime git

https://github.com/SublimeGit/SublimeGit/commit/3832541ad1500ec709e33d3852d13f4877de34c5

**Comment by divinites** [comment]
good suggestion, I will see to this problem soon and push an update. Thanks.

**Comment by divinites** [comment]
done with commit & bdddd72d201c8f8d19e5f64cf801de4e4a78734e if it works, could you please give feedbacks here so that I could close this issue, thanks.

**Comment by docsteveharris** [comment]
amazing! thank you
to open an issue in list view then pressing 'enter' just moves me to the next issue down (like 'j' or 'down-arrow' - but if I hit 'i' (insert mode) then 'enter' it works

**Comment by divinites** [comment]
So it works now?

**Comment by docsteveharris** [comment]
So before, even if I entered 'insert' mode, hitting enter would not take me to the issue.
Now, if I enter 'insert' mode, it does.
So for me, this is fine because I can make it work 👍 - thanks. But I guess, it would also be fair to say that vintageous does not seem to be disabled (I still have access to the vim keybindings).
Anyway, awesome plugin - thankyou 😃

**Comment by divinites** [comment]
Thanks for your feedback. That's interesting, since I basically implemented the same code as sublime git, I will have a look at it again and probably I will install vintageous to test whether it is disabled.

**Comment by divinites** [comment]
I installed vintageous and I cannot replicate this bug. Sorry, but if I cannot replicate it, I am afraid that I cannot fix it. I have similar issues with gitsavvy + vintageous before--the commands only work in insert mode. I will use GitHubIssue + vintageous for a while, to see if someday I can see the bug, Thanks.

**Comment by docsteveharris** [comment]
Fair enough - it's probably something local on my machine now. thanks for the update -  feel free to close
